# Generated by Django 4.1.7 on 2023-11-30 16:30

from django.db import migrations, models

##
class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_course_discount_course_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=255)),
                ("option1", models.CharField(max_length=255)),
                ("option2", models.CharField(max_length=255)),
                ("option3", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
            ],
        ),
    ]
