# Generated by Django 4.1.7 on 2023-11-30 16:46

from django.db import migrations

##
class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
